// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cpu} from '../models';
import {time} from '../models';

export function GetCpuInfo():Promise<Array<cpu.InfoStat>>;

export function GetCpuUses(arg1:time.Duration,arg2:boolean):Promise<Array<number>>;
