// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuInfo() {
  return window['go']['system']['System']['GetCpuInfo']();
}

export function GetCpuUses(arg1, arg2) {
  return window['go']['system']['System']['GetCpuUses'](arg1, arg2);
}
