// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuInfo() {
  return window['go']['systeminfo']['CpuInfo']['GetCpuInfo']();
}

export function GetCpuUses() {
  return window['go']['systeminfo']['CpuInfo']['GetCpuUses']();
}

export function GetPhysicalCount(arg1) {
  return window['go']['systeminfo']['CpuInfo']['GetPhysicalCount'](arg1);
}
